#ifndef INC_MAINMENU_H_
#define INC_MAINMENU_H_

#define MAIN_MENU_BROWSE_ROMS 0
#define MAIN_MENU_NEW_ROM 1
#define MAIN_MENU_SETTINGS 2
#define MAIN_MENU_SERVICE_MENU 3

#define MAIN_MENU_FONT FONT_STANDARD_6
#define MAIN_MENU_VERSION_FONT FONT_ULTRASLIMFONT_8

void main_menu_loop();

#endif /* INC_MAINMENU_H_ */
