#ifndef INC_MAINMENU_H_
#define INC_MAINMENU_H_

#include "ff.h"

#define MAIN_MENU_FONT FONT_STANDARD_6
#define MAIN_MENU_VERSION_FONT FONT_ULTRASLIMFONT_8

typedef enum
{
  MAIN_MENU_BROWSE_ROMS,
  MAIN_MENU_NEW_ROM,
  MAIN_MENU_SETTINGS,
  MAIN_MENU_SERVICE_MENU,
  MAIN_MENU_NONE
} MAIN_MENU_SELECTION;

void main_menu_loop();

#endif /* INC_MAINMENU_H_ */
